/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test_jitpack_repo.app;

import test_jitpack_repo.list.LinkedList;

import static test_jitpack_repo.utilities.StringUtils.join;
import static test_jitpack_repo.utilities.StringUtils.split;
import static test_jitpack_repo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
